cmd_drivers/misc/mediatek/masp/asf/auth/sec_wrapper.o := /home/olegsvs/Android/aarch64-linux-android-4.9/bin/aarch64-linux-android-gcc -Wp,-MD,drivers/misc/mediatek/masp/asf/auth/.sec_wrapper.o.d  -nostdinc -isystem /home/olegsvs/Android/aarch64-linux-android-4.9/bin/../lib/gcc/aarch64-linux-android/4.9/include -I/home/olegsvs/5/Q37/alps/kernel-3.10/arch/arm64/include -Iarch/arm64/include/generated  -Iinclude -I/home/olegsvs/5/Q37/alps/kernel-3.10/arch/arm64/include/uapi -Iarch/arm64/include/generated/uapi -I/home/olegsvs/5/Q37/alps/kernel-3.10/include/uapi -Iinclude/generated/uapi -include /home/olegsvs/5/Q37/alps/kernel-3.10/include/linux/kconfig.h -D__KERNEL__ -mlittle-endian -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -fno-delete-null-pointer-checks -Werror=format -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -O2 -mgeneral-regs-only -fno-pic -Wframe-larger-than=1400 -fno-stack-protector -Wno-unused-but-set-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-var-tracking-assignments -g -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -I/home/olegsvs/5/Q37/alps/kernel-3.10/drivers/misc/mediatek/mach/mt6735/include -Idrivers/misc/mediatek/masp/asf/asf_inc -Idrivers/misc/mediatek/masp/asf/asf_inc -Idrivers/misc/mediatek/masp/asf/asf_inc -Idrivers/misc/mediatek/masp/module    -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(sec_wrapper)"  -D"KBUILD_MODNAME=KBUILD_STR(sec)" -c -o drivers/misc/mediatek/masp/asf/auth/sec_wrapper.o drivers/misc/mediatek/masp/asf/auth/sec_wrapper.c

source_drivers/misc/mediatek/masp/asf/auth/sec_wrapper.o := drivers/misc/mediatek/masp/asf/auth/sec_wrapper.c

deps_drivers/misc/mediatek/masp/asf/auth/sec_wrapper.o := \

drivers/misc/mediatek/masp/asf/auth/sec_wrapper.o: $(deps_drivers/misc/mediatek/masp/asf/auth/sec_wrapper.o)

$(deps_drivers/misc/mediatek/masp/asf/auth/sec_wrapper.o):
