cmd_drivers/misc/mediatek/fmradio/dummy.o := /home/olegsvs/Android/aarch64-linux-android-4.9/bin/aarch64-linux-android-gcc -Wp,-MD,drivers/misc/mediatek/fmradio/.dummy.o.d  -nostdinc -isystem /home/olegsvs/Android/aarch64-linux-android-4.9/bin/../lib/gcc/aarch64-linux-android/4.9/include -I/home/olegsvs/5/Q37/alps/kernel-3.10/arch/arm64/include -Iarch/arm64/include/generated  -Iinclude -I/home/olegsvs/5/Q37/alps/kernel-3.10/arch/arm64/include/uapi -Iarch/arm64/include/generated/uapi -I/home/olegsvs/5/Q37/alps/kernel-3.10/include/uapi -Iinclude/generated/uapi -include /home/olegsvs/5/Q37/alps/kernel-3.10/include/linux/kconfig.h -D__KERNEL__ -mlittle-endian -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -fno-delete-null-pointer-checks -Werror=format -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -O2 -mgeneral-regs-only -fno-pic -Wframe-larger-than=1400 -fno-stack-protector -Wno-unused-but-set-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-var-tracking-assignments -g -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -I/home/olegsvs/5/Q37/alps/kernel-3.10/drivers/misc/mediatek/mach/mt6735/include -D MTK_WCN_REMOVE_KERNEL_MODULE -I/home/olegsvs/5/Q37/alps/kernel-3.10/drivers/misc/mediatek/mach/mt6735/include -DWMT_PLAT_ALPS=1 -DMT6627_FM -DMT6625_FM -Idrivers/misc/mediatek/fmradio/inc -Idrivers/misc/mediatek/fmradio/mt6627/inc -Idrivers/misc/mediatek/fmradio/../connectivity/conn_soc/common/include -Idrivers/misc/mediatek/fmradio/../connectivity/conn_soc/common/linux/include -Idrivers/misc/mediatek/fmradio/../connectivity/common_detect    -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(dummy)"  -D"KBUILD_MODNAME=KBUILD_STR(dummy)" -c -o drivers/misc/mediatek/fmradio/dummy.o drivers/misc/mediatek/fmradio/dummy.c

source_drivers/misc/mediatek/fmradio/dummy.o := drivers/misc/mediatek/fmradio/dummy.c

deps_drivers/misc/mediatek/fmradio/dummy.o := \

drivers/misc/mediatek/fmradio/dummy.o: $(deps_drivers/misc/mediatek/fmradio/dummy.o)

$(deps_drivers/misc/mediatek/fmradio/dummy.o):
